[build]
  # Statische Website - Build Script f端r Environment Variables
  publish = "."
  command = "node setup-env.js"

# Environment Variables Injection Script
[build.environment]
  NODE_VERSION = "18"

# WICHTIG: SPA Redirects f端r Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Content Security Policy f端r Firebase
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://www.gstatic.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://*.firebaseio.com https://*.googleapis.com https://unpkg.com; font-src 'self'; object-src 'none'; media-src 'self'; frame-src 'none';"

# Cache-Optimierung
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.css"  
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Firebase spezifische Headers
[[headers]]
  for = "/fireconfig.js"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

# Environment Variables injection f端r Firebase
[[headers]]
  for = "/env-config.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
